### PR TITLE
Update buildTypeDefsAndResolvers.ts

### PR DESCRIPTION
**Pull request by Carassale**
Adds a method to build TypeDefs and Resolvers in Sync mode.

### CODE REVIEW

**Comment by MichalLytek** [comment]
Could you also add tests, update docs and add a changelog entry?

**Comment by Carassale** [comment]
> Could you also add tests, update docs and add a changelog entry?

done, do you think it would be okay?

**Comment by carlocorradini** [comment]
> Adds a method to build TypeDefs and Resolvers in Sync mode.

I really need this feature, thanks @Carassale! 🎉✨

**Comment by Carassale** [comment]
I need this feature for some projects I will be working on soon. @MichalLytek do you think it can be approved?

**Review by MichalLytek — APPROVED** [review]
Look great, thanks! 🙏

**Comment by MichalLytek** [comment]
@Carassale I've added some docs change, smaller test suite, improved naming and changelog entry. Now it's ready to merge 💪

**Pull request merged**
