### PR TITLE
Add `browser` field to package.json for frontend use

### PR DESCRIPTION
**Pull request by campbellwmorgan**
* The `browser-shim` works nicely when trying to share code between
  frontend and backend, however manual overrides can be tricky
* Many build systems (including webpack) will take the script from
  the `browser` field simplifying this process

### CODE REVIEW

**Review by marcoklein — APPROVED** [review]

**Comment by itpropro** [comment]
Any updates here @MichalLytek? I know its a small change, but it would help me fixing this in many projects and for the future.

**Comment by MichalLytek** [comment]
I'm not convinced about this. 

TypeGraphQL can also normally work on frontend (e.g. https://github.com/MichalLytek/type-graphql/tree/master/examples/apollo-client). And looks like with this change, bundlers will start using shim instead of the real package 😕

**Comment by ibilux** [comment]
> I'm not convinced about this.
> 
> TypeGraphQL can also normally work on frontend (e.g. https://github.com/MichalLytek/type-graphql/tree/master/examples/apollo-client). And looks like with this change, bundlers will start using shim instead of the real package confused

It does not work on framework like SvelteKit for frontend (but it does work for backend).

**Comment by ibilux** [comment]
This PR fixed the problem in SvelteKit !

**Comment by MichalLytek** [comment]
@campbellwmorgan 
I've updated your branch with recent `master` and updated the entry to match the new build folders introduced by #1400.
Thanks for your contribution! ❤️

**Review by MichalLytek — APPROVED** [review]

**Pull request merged**
