### PR TITLE
Update directives.md

### PR DESCRIPTION
**Pull request by meunierfrederic**
Some highlights to print the schema with directives

### CODE REVIEW

**Comment by carlocorradini** [comment]
This is already available in the documentation: https://github.com/MichalLytek/type-graphql/blob/master/docs/emit-schema.md#emit-schema-with-custom-directives

**Comment by carlocorradini** [comment]
Do you want to update something in the current documentation to add a reference to the emit-schema file?

**Comment by meunierfrederic** [comment]
@carlocorradini when teammates have read the note, they simply gave up, they though it was just not possible to print the schema with directive. Yes maybe a reference to emit-schema-file shall be appreciated by others.

**Comment by carlocorradini** [comment]
@meunierfrederic Awesome
Can you create a new simple PR to reference the file?

**Comment by carlocorradini** [comment]
Something like (citing your PR):
> You can still use 3rd party libraries such as graphql-tools to print schema with directives
For more information...

**Pull request closed without merging**
