### PR TITLE
internal: removed postinstall script

### LINKED ISSUE #1339: Post-install script causes failures
**Describe the Bug**
When installing the lib on Windows it errors with the line `npm ERR! The token '||' is not a valid statement separator in this version.`.

**To Reproduce**
Install the library.

**Expected Behavior**
To install correctly.

**Cause**
The issue is that you have a hacky post-install step in the `package.json` which errors depending on the scripting environment of the installer.

**Logs**
```
PS C:\...> npm i
npm ERR! code 1
npm ERR! path C:\...\node_modules\type-graphql
npm ERR! command failed
npm ERR! command powershell -c node ./dist/postinstall || exit 0
npm ERR! At line:1 char:25
npm ERR! + node ./dist/postinstall || exit 0
npm ERR! +                         ~~
npm ERR! The token '||' is not a valid statement separator in this version.
npm ERR!     + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
npm ERR!     + FullyQualifiedErrorId : InvalidEndOfLine

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\tmp\npm-cache\_logs\2022-08-28T22_11_38_524Z-debug-0.log
```

**Environment (please complete the following information):**

OS: Windows
Node: v16.15.0

```
Name                           Value
----                           -----
PSVersion                      5.1.22000.653
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.653
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

**Additional Context**
This is a pretty clear-cut case of postinstall abuse, but I can work around it with the `--ignore-scripts` flag or a fork. I'd recommend you look at using the `npm fund` process now.

### PR DESCRIPTION
**Pull request by carlocorradini**
Fix #1339

### CODE REVIEW

**Comment by MichalLytek** [comment]
Can you also add npm fund entry?

**Comment by carlocorradini** [comment]
Already available at line 109 :)

**Comment by MichalLytek** [comment]
Ah so I did it long time ago 😅

**Comment by MichalLytek** [comment]
@carlocorradini Can we add also a link to github sponsors?

**Comment by carlocorradini** [comment]
Where?

**Comment by carlocorradini** [comment]
> Where?

I'll modify `funding` as an array instead of object

**Comment by carlocorradini** [comment]
@MichalLytek Done! 🥳

**Review by MichalLytek — APPROVED** [review]

**Pull request merged**
