### PR TITLE
feat: mikro-orm example

### PR DESCRIPTION
**Pull request by driescroons**
added example as a submodule

### CODE REVIEW

**Comment by driescroons** [comment]
@MichalLytek what do you think? can't assign you as a reviewer

**Comment by MichalLytek** [comment]
TBH, I don't find attaching external repos as submodules useful.

I'm going to create my own example usage of mikro orm, so I will just link your repo as the more advanced, real world use example. WDYT? 😉

**Comment by driescroons** [comment]
Up to you, if you define what you'd like, I can create it. I'd love to collaborate on the repository 😀

**Comment by MichalLytek** [comment]
Closing as supersed by ba86a6b79fcb91bac3a276e49578e9590acd2e1c 🔒

**Pull request closed without merging**
