### PR TITLE
Changes arrayProp to prop as arrayProp is deprecated

### PR DESCRIPTION
**Pull request by smolinari**
Hope this is ok. 

Refers to this: https://github.com/MichalLytek/type-graphql/issues/117#issuecomment-645810830

Scott

### CODE REVIEW

**Comment by smolinari** [comment]
@MichalLytek - Sorry, but I'm not sure what your comment is implying. 

Scott

**Comment by MichalLytek** [comment]
` @Property({ items: Rate, default: [] })`

**Comment by smolinari** [comment]
> ` @Property({ items: Rate, default: [] })`

Yes, `Rate` is a Class and a sub-document, right? 

Scott

**Comment by MichalLytek** [comment]
@smolinari `items` is deprecated, use `type` from 7.2.0

**Comment by smolinari** [comment]
Ah. Geez. Thanks for catching that. 

Scott

**Comment by smolinari** [comment]
Hope that is correct now. Docs aren't super clear on what the value for `type` should be. I gathered this from the Typegoose change discussions.

Scott

**Pull request merged**
