### PR TITLE
Change to const to grab the `Context` and `Info`

### PR DESCRIPTION
**Pull request by timot7782**
Changed to const so that we can get the context and info if we need to

### CODE REVIEW

**Review by russelshane — APPROVED** [review]
👍👍

**Review by MichalLytek — CHANGES_REQUESTED** [review]
But why?

**Comment by timot7782** [comment]
> But why?

So that we can pass the context and info (fields) from apollo to the underlaying backend (if needed).

In our team, we need to grab the access token that is passed from the consumer to our microservices.

**Comment by MichalLytek** [comment]
Yeah but:
1) You can do that with `function`, no need for `const`.
2) This is example and the example code is not using `context` nor `info`. Do you always declare unused parameters?
3) You can do that in your team, in your code, no need to introduce unused parameters in the examples. Have you referred to apollo federation docs about the `resolveReference` functions? Maybe we should create a docs page about integrating with `apollo-federation` instead?

So closing this PR as I don't see a reason for such code change 🔒 
Let's discuss your context and your issues, instead of your proposal of fixing the unknown root cause.

**Pull request closed without merging**
