### PR TITLE
Docs, add dark mode feature

### LINKED ISSUE #729: Add dark mode option to Type graphql homepage
I always read your docs, like this XD
I change the CSS, everytime I switch topic,

image

### PR DESCRIPTION
**Pull request by king-leonidas1337**
Closes #729

### CODE REVIEW

**Review by MichalLytek — CHANGES_REQUESTED** [review]
Looks nice, however I would make the menu items brighter, now they are not contrast enough:
image

And the switch can't be a raw button placed in corner - please do something similar to Docusaurus 2.0:
image

**Comment by king-leonidas1337** [comment]
Where you want the button to be located? I consider interacting with docusaurus navbar is pretty tough.

**Comment by MichalLytek** [comment]
Navbar is the right place:

image

> I consider interacting with docusaurus navbar is pretty tough.

I agree, that's why I haven't dig into that yet.

**Review by MichalLytek — CHANGES_REQUESTED** [review]
1) You need to change `code` blocks background color to `rgb(255 255 255 / 5%)`

image

2) The right menu items are too dark

image

3) Make use of the new CSS `prefers-color-scheme` selector:
https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme

4) The code examples could be also with `opacity: 0.9` as they have too much saturation for dark mode.

image

5) Urls are too dark, please make them brighter (`#6daff0`):

image

6) Please check every page of the docs:

image

7) Make that toggle look non-coarse - it's visible on each page 😱 
Please search for some css inspiration how to make it look like a normal switch component.

image

**Comment by king-leonidas1337** [comment]
My button actually looks like this: 
buttons
Somehow i failed pushing its css file

**Comment by MichalLytek** [comment]
> Somehow i failed pushing its css file

@king-leonidas1337 So can you amend your commit and push the file? I see `@import "./button.css";` but the file doesn't exist.

**Comment by king-leonidas1337** [comment]
Button styling moved to custom.css.
Made changes you expected.
Changed .projectTitle color.
Changed blockquote color.

**Comment by MichalLytek** [comment]
@king-leonidas1337 Last change: `#c04392` and `#7f2f61` as the toggle button background 😉 
The green one doesn't match to the site's color palette.

**Comment by king-leonidas1337** [comment]
@MichalLytek ready

**Comment by MichalLytek** [comment]
@king-leonidas1337 Looks good, I've fixed the default color scheme behavior.

However, there's something wrong with the colors on homepage, different shadow of white/gray:

opera_jLBKDFUgCf

0bSUbOZ9LT

**Comment by king-leonidas1337** [comment]
@MichalLytek done

**Comment by MichalLytek** [comment]
@king-leonidas1337 Thanks! Let's merge then 🚀

**Review by MichalLytek — APPROVED** [review]

**Pull request merged**
