### PR TITLE
Upgrade codebase to GraphQL v16

### PR DESCRIPTION
**Pull request by MichalLytek**
WIP

### CODE REVIEW

**Comment by carlocorradini** [comment]
It's happening 😍🥳

**Comment by alvis** [comment]
It's coming!!! ❤️❤️❤️

**Comment by orefalo** [comment]
nice!

**Comment by EstebanBorai** [comment]
Thanks so much for the hard work @MichalLytek!

**Comment by angelo-moreira** [comment]
this is great, thank you, I have asked the company that I work for to contribute to this project.
❤️❤️❤️❤️❤️

**Comment by noxend** [comment]
@MichalLytek thank you! 🙌❤️

**Comment by hkd987** [comment]
I thought @MichalLytek had died or moved out to the woods leaving all traces of nodejs behind, but he has risen with an amazing Draft PR for us to all admire. May the gods of nodejs bless this draft PR with speed, no bugs, and a quick merge. 

All kidding aside I really thought this project had died, and was just starting to plan our exit from type-graphql, but this PR gives me a warm fuzzy that we are headed in the right direction.

**Comment by jessekrubin** [comment]
> I thought @MichalLytek had died or moved out to the woods leaving all traces of nodejs behind, but he has risen with an amazing Draft PR for us to all admire. May the gods of nodejs bless this draft PR with speed, no bugs, and a quick merge.

@hkd987 Much like Keith Richards (of the rolling stones), @MichalLytek cannot be killed by conventional weapons. He is nearly indestructible.

**Comment by bnussman** [comment]
This is exciting 🚀

**Comment by productdevbook** [comment]
reflect-metadata Can it use something else instead because it doesn't support esm. It's old.

**Comment by kt390256** [comment]
Hi Michal, this is amazing work and thank you for this! I was doing some researches and I found that the current version of tGQL only works with graphql 15.3.0, just want to know if v2.0 will be compatible with any other 15.x version(ideally 15.5) or 16.x version? Thanks in advance!

**Comment by vuki656** [comment]
> Hi Michal, this is amazing work and thank you for this! I was doing some researches and I found that the current version of tGQL only works with graphql 15.3.0, just want to know if v2.0 will be compatible with any other 15.x version(ideally 15.5) or 16.x version? Thanks in advance!

Yes it will, 16.6. [check the diff.](https://github.com/MichalLytek/type-graphql/pull/1331/files#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR4)

**Comment by MichalLytek** [comment]
> reflect-metadata Can it use something else instead because it doesn't support esm. It's old.

@productdevbook Please list something else we can use for shimming reflect metadata api

**Comment by productdevbook** [comment]
> > reflect-metadata Can it use something else instead because it doesn't support esm. It's old.
> 
> @productdevbook Please list something else we can use for shimming reflect metadata api

https://github.com/abraham/reflection

**Comment by MichalLytek** [comment]
@productdevbook Have you tried using that? TypeGraphQL doesn't force to use `reflect-metadata`:
https://github.com/MichalLytek/type-graphql/blob/91ca9b12f84369423372ab480e6685437a59c675/src/metadata/utils.ts#L60-L68
https://github.com/MichalLytek/type-graphql/blob/91ca9b12f84369423372ab480e6685437a59c675/src/errors/ReflectMetadataMissingError.ts#L1-L10

**Comment by kt390256** [comment]
@vuki656 thanks much! sorry just one more question, do you know when will this be released? very exciting about this

**Comment by vuki656** [comment]
> @vuki656 thanks much! sorry just one more question, do you know when will this be released? very excited about this

I don't think there is a date.

**Comment by BeeeQueue** [comment]
> Maybe we can just list `abraham/reflection` and `core-js/es7/reflect` in docs as the alternatives?

`@abraham/reflection` seems to work in my project 👍

**Comment by MaxAst** [comment]
Hey @MichalLytek, I'm happy to contribute to this PR in case you need support! Would just need some guidance w.r.t what's still left to do

**Comment by itpropro** [comment]
> Hey @MichalLytek, I'm happy to contribute to this PR in case you need support! Would just need some guidance w.r.t what's still left to do

If we work on #1356, @MaxAst can also get a contribution towards his hacktoberfest stats 💪

**Comment by dragurimu** [comment]
Dear ETA?
I am facing 2510 incompatibilities with mercurius that have recently stopped working I have released several posts to the-guild

**Comment by arimus** [comment]
Any word @MichalLytek at what is left and how we might be able to help?

I'm currently trying to create an Apollo server v4 Hapijs adapter, but looks like upgrading Apollo server pushes graphql to v16 and thus triggers this issue in the project I'm using to do the dev.

**Comment by MichalLytek** [comment]
If someone wants to help, please checkout the branch and run every example to see if all the presented features works ok. The one I've updated the codebase (like apollo federation or mikro-orm) should be checked but e.g. subscriptions might not work.

**Comment by arimus** [comment]
@MichalLytek started going through examples. Ran into an issue with the "extensions" example. Not sure if you just want them in this thread or elsewhere. Posting this one here, but can update elsewhere if more useful (e.g. new issues, etc.)

```
{
  "errors": [
    {
      "message": "Service with \"MaybeConstructable<ExampleResolver>\" identifier was not found in the container. Register it before usage via explicitly calling the \"Container.set\" function or using the \"@Service()\" decorator.",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "recipes"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "name": "ServiceNotFoundError",
          "normalizedIdentifier": "MaybeConstructable<ExampleResolver>",
          "stacktrace": [
            "ServiceNotFoundError: Service with \"MaybeConstructable<ExampleResolver>\" identifier was not found in the container. Register it before usage via explicitly calling the \"Container.set\" function or using the \"@Service()\" decorator.",
            "    at ContainerInstance.get (/Users/arimus/workspace/type-graphql/node_modules/src/container-instance.class.ts:75:11)",
            "    at Function.get (/Users/arimus/workspace/type-graphql/node_modules/src/container.class.ts:61:32)",
            "    at IOCContainer.getInstance (/Users/arimus/workspace/type-graphql/src/utils/container.ts:57:22)",
            "    at /Users/arimus/workspace/type-graphql/src/resolvers/create.ts:32:67",
            "    at field.resolve (/Users/arimus/workspace/type-graphql/node_modules/apollo-server-core/src/utils/schemaInstrumentation.ts:106:18)",
            "    at executeField (/Users/arimus/workspace/type-graphql/node_modules/graphql/execution/execute.js:481:20)",
            "    at executeFields (/Users/arimus/workspace/type-graphql/node_modules/graphql/execution/execute.js:413:20)",
            "    at executeOperation (/Users/arimus/workspace/type-graphql/node_modules/graphql/execution/execute.js:344:14)",
            "    at execute (/Users/arimus/workspace/type-graphql/node_modules/graphql/execution/execute.js:136:20)",
            "    at execute (/Users/arimus/workspace/type-graphql/node_modules/apollo-server-core/src/requestPipeline.ts:500:34)"
          ]
        }
      }
    }
  ],
  "data": null
}
```

**Comment by MichalLytek** [comment]
I've published the current state of this branch as `type-graphql@2.0.0-beta.1`.

**Comment by carlocorradini** [comment]
I've tested it in my project and can confirm that v2.0 works like a charm.

**Comment by carlocorradini** [comment]
@MichalLytek 
Instead of generic `Error`, the error classes related to `GraphQL` can extend [GraphQLError](https://github.com/graphql/graphql-js/blob/main/src/error/GraphQLError.ts).

**Comment by okaforcj** [comment]
> @MichalLytek 
> Instead of generic `Error`, the error classes related to `GraphQL` can extend [GraphQLError](https://github.com/graphql/graphql-js/blob/main/src/error/GraphQLError.ts).

Not sure if its related but i bumped to apollo server v4 and used this beta release and im not getting the class-validator validation errors in the extensions like this: https://github.com/MichalLytek/type-graphql/issues/258#issuecomment-466637130,
im instead getting . not sure if im configuring it wrong @MichalLytek  @carlocorradini 
``` json
{
  "data": {},
  "errors": [
    {
      "message": "Argument Validation Error",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "textPost"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "stacktrace": [
          "Error: Argument Validation Error",
          "    at validateArg (/<local-path>/node_modules/type-graphql/dist/resolvers/validate-arg.js:55:15)",
          "    at processTicksAndRejections (node:internal/process/task_queues:96:5)",
          "    at async Promise.all (index 0)"
        ]
      }
    }
  ]
}
```

running on an express server 
``` js script
 const server = new ApolloServer({
        schema: schema,
    });
    await server.start();
    app.use(
        '/graphql',
        express.json(),
        expressMiddleware(server, {
            context: async ({req}) => ({token: req.headers.token}),
        }),
    );

```

i added this to intercept and log 
``` js script
  formatError: (formattedError,error: any) => {
            if (error.originalError instanceof ArgumentValidationError) {
                const { extensions, locations, message, path } = error;

                // error.extensions.code = 'GRAPHQL_VALIDATION_FAILED';
                console.log(error)
                // return {
                //     extensions,
                //     locations,
                //     message,
                //     path,
                // };
            }
            return formattedError;
        }
```

but it doesnt produces have the validation errors

**Comment by carlocorradini** [comment]
@okaforcj For me it's working without any problems:
img
## Context:
### Project
<https://github.com/carlocorradini/reCluster/tree/main/server>
### `main.ts` (Apollo Server, etc...)
<https://github.com/carlocorradini/reCluster/blob/main/server/src/main.ts>
### Custom errors
<https://github.com/carlocorradini/reCluster/tree/main/server/src/errors>
### `formatError.ts`
<https://github.com/carlocorradini/reCluster/blob/main/server/src/helpers/formatError.ts>

**Comment by okaforcj** [comment]
> @okaforcj For me it's working without any problems (TypeGraphQL v2 & Apollo Server v4): img
> 
> ## Context:
> ### Project
> https://github.com/carlocorradini/reCluster/tree/main/server
> 
> ### `main.ts` (Apollo Server, etc...)
> https://github.com/carlocorradini/reCluster/blob/main/server/src/main.ts
> 
> ### Custom errors
> https://github.com/carlocorradini/reCluster/tree/main/server/src/errors
> 
> ### `formatError.ts`
> https://github.com/carlocorradini/reCluster/blob/main/server/src/helpers/formatError.ts

Thanks a lot, works like a charm. Sorry for disturbing you guys but thanks for the amazing library @MichalLytek and @carlocorradini  I really appreciate the help.

**Comment by carlocorradini** [comment]
@okaforcj What was the error? :)

**Comment by okaforcj** [comment]
> @okaforcj What was the error? :)

there was no error, i just added your configuration to format the error. is that in the documentation somewhere and i missed it ?

this bit @carlocorradini 

``` js script
  formatError: (formattedError,error: any) => {
            const originalError = unwrapResolverError(error);
            if (originalError instanceof ArgumentValidationError) {
               return new ValidationError(originalError.validationErrors);
            }
            return formattedError;
        }
```

**Comment by flmuel** [comment]
Everything is working on my end :)

**Comment by rafaell-lycan** [comment]
@MichalLytek there's any benchmark comparison from v1 to v2?

Also, in terms of DX, any major improvements?

I can't wait to see it alive (maybe before Xmas?) and suggest the update in my company ❤️

**Comment by MichalLytek** [comment]
@rafaell-lycan See the changelog.md

**Comment by ralphstodomingo** [comment]
Tested this too in a project that was using decorators from typegoose+class-validator, mutations and queries work well, thanks.

Subscriptions however, validation seems to run after the `@Subscription` resolver returns any value, and both of our models' internal validate fns (called in constructor of model) and `class-validator` decorators seem to be called with undefined values, resulting in errors.

The only workaround I've found so far is to remove all uses of class-validator and our internal validate fns, which is weird. Proper deps are installed, and it's none of the existing middleware that was causing this.

**Comment by cjnoname** [comment]
Is there any plan to release it?

**Comment by cjnoname** [comment]
Any plan for release?

**Comment by carlocorradini** [comment]
Hey everyone, I've created **PR #1400** where I'm trying to increase the **maintainability** of the project.
**Add your thoughts if you have any ideas or something similar!**

**Comment by john-dodson** [comment]
I'm having some issues where any field that I denote as a Int or a Float throws a `Cannot determine GraphQL input type` error when building the schema. Examples:

`
@Field((_type) => Int)
public fee: number
`

`
@Field((_type) => Float)
public fee: number
`

**Comment by carlocorradini** [comment]
@john-dodson 
Please add more information.
Have you tried using scalars from `graphql` (`Int` and `Float` are aliases):
```ts
import { GraphQLInt, GraphQLFloat } from 'graphql';

@Field(() => GraphQLInt)
public fee: number

@Field(() => GraphQLFloat )
public fee: number
```

**Comment by john-dodson** [comment]
> @john-dodson Please add more information. Have you tried using scalars from `graphql` (`Int` and `Float` are aliases):
> 
> ```ts
> import { GraphQLInt, GraphQLFloat } from 'graphql';
> 
> @Field(() => GraphQLInt)
> public fee: number
> 
> @Field(() => GraphQLFloat )
> public fee: number
> ```

Same issue if I use GraphQLInt and GraphQLFloat.

**Comment by MichalLytek** [comment]
All tests are passing so all works like in the `v1.x` releases. @john-dodson your issue is 100% related to multiple `graphql-js` instances in your `node_modules` - importing type classes from different npm package or yarn workspaces project. Search for issues on this repo about this.

**Comment by john-dodson** [comment]
> All tests are passing so all works like in the `v1.x` releases. @john-dodson your issue is 100% related to multiple `graphql-js` instances in your `node_modules` - importing type classes from different npm package or yarn workspaces project. Search for issues on this repo about this.

Yeah, as per your comment I blew away the entire repo and checked it out again and it started working. Thanks.

**Comment by holzerch** [comment]
> All tests are passing so all works like in the `v1.x` releases. 
@MichalLytek any plans on publishing the current state as new beta version?

**Comment by bombillazo** [comment]
Still interested in having this release, eve in a preview or beta to test!

**Comment by carlocorradini** [comment]
@bombillazo 

Uninstall: 
```sh
npm uninstall type-graphql
```
Install `@next`:
```sh
mom install type-graphql@nexr
```

**Comment by abjrcode** [comment]
Are there still any blockers for this release?

**Comment by cjnoname** [comment]
We are waiting for this release too. Is there a chance to release a new Beta/RC version to npm?

**Comment by MichalLytek** [comment]
@cjnoname You can install `2.0.0-beta.1` from npm:
https://www.npmjs.com/package/type-graphql/v/2.0.0-beta.1

**Comment by cjnoname** [comment]
> @cjnoname You can install `2.0.0-beta.1` from npm: https://www.npmjs.com/package/type-graphql/v/2.0.0-beta.1

Thanks for your reply mate. I saw it was release three months ago, so I doubt whether it contains all the latest changes or not..

Cheers,
CJ

**Comment by holzerch** [comment]
`next` and `2.0.0-beta.1` both point to the 3 months old release.
image
So the question remains whether it would be possible to publish a new beta version 🙏

**Comment by MichalLytek** [comment]
It would not contain any change. The branch is just rebased from time to time

**Comment by bombillazo** [comment]
Also, any documented changes to have an idea about the breaking changes?

**Comment by MichalLytek** [comment]
@abjrcode Unfortunately, it's the only legit way to detect whether it's an arrow function or ES6 class. This check works for all other kind of checks, with middlewares too.
Happy to see a proposal of better mechanism, maybe new ES have something more sophisticated than printing the source code and regexing for class/function keyword.

**Comment by thi-marques** [comment]
> @abjrcode Unfortunately, it's the only legit way to detect whether it's an arrow function or ES6 class. This check works for all other kind of checks, with middlewares too. Happy to see a proposal of better mechanism, maybe new ES have something more sophisticated than printing the source code and regexing for class/function keyword.

I'm not 100% sure, but I think this may help:

``` typescript
function isConstructor(fn?: any) {
  return (
    typeof fn === 'function' &&
    fn?.prototype?.constructor === fn &&
    fn !== Symbol
  )
}
```

I adapteded it from [How to check if a Javascript function is a constructor](https://stackoverflow.com/a/70810697/7273790)

**Comment by cjnoname** [comment]
Hi @MichalLytek ,

We have successfully upgraded to v2 beta and it works perfectly. Looking forward for the formal release.

Thanks

**Comment by bombillazo** [comment]
Been testing for a few days, no issues so far and we were able to migrate to Apollo 4 thanks to this!

**Comment by loan-laux** [comment]
Same here.

**Comment by fknop** [comment]
Can the beta version be considered stable? As in API changes?
Any ETA on the final release? :)

**Comment by carlocorradini** [comment]
Awesome! 😎🥳

**Comment by MichalLytek** [comment]
The PR has been renamed to GraphQL v16 support as that was the main scope of the changes.

The work on the `v2.0` release will be done step-by-step on the `master` branch.
More info here: https://github.com/MichalLytek/type-graphql/issues/1418

**Pull request merged**
