### PR TITLE
New Option for Resolvers: Skip schema emit

### PR DESCRIPTION
**Pull request by Xzas22**
I ran in to a situation where I wanted a certain resolver to not emit to the schema during the buildSchema command. 

Specifically, I created a factory resolver class, and for certain instantiations, I want delete${item} to be emitted, and for others I do not. 

Having the ability to mark resolver functions as "skipSchemaEmit: True" would be majorly helpful. 

I added in the necessary options and tests, and confirmed everything works as intended. 

BTW: I am still pretty new to coding in general so my tests are not what I would call "elegant"

### CODE REVIEW

**Comment by Xzas22** [comment]
This is my first ever pull request so if I did something wrong please let me know. Im always open to advice on getting better, Thanks!

**Comment by MichalLytek** [comment]
If you need to skip emitting in schema, just comment the decorator 😄 
This kind of API is really awkward 😕

**Comment by Xzas22** [comment]
Its for use with abstract classes. For example:

The factory:
`
export const createBaseResolvers = <E extends AbstractEntity>(
	name: string,
	entity: E,
	inputType: Partial<E> | DeepPartial<E>,
	emitDelete: boolean = false
) => {
	@Resolver(() => entity, { isAbstract: true })
	abstract class BaseResolver {
		protected entity: Repository<E> = entity as any;

		@Query(() => entity, {
			name: `get${name}`,
			description: `Returns a single ${name}`,
			skipSchemaEmit: emitDelete
		})
		async getOne(@Arg(`${name}Id`) id: number): Promise<E | undefined> {
			return await this.entity.findOne(id);
		}

//.... others
`

The instantiation:
`
const BaseCompany = createBaseResolvers('Company', Company, CreateCompanyInput, True);

@Resolver(() => Company)
export class CompanyResolvers extends BaseCompany {
//...whatever other resolvers I want
}
`

This way I have one factory function that I extend from, and when I need to have certain resolvers from that factory on or off I simply add the necessary "TRUE" to their respective skipSchemaEmit option.

**Comment by MichalLytek** [comment]
You can still do that just by not calling the decorator factory:
```ts
const Skip: ClassDecorator & PropertyDecorator & MethodDecorator & ParameterDecorator = () => {};
```

```ts
abstract class BaseResolver {
  @(emitDelete ? Query(() => entity, {
    name: `get${name}`,
    description: `Returns a single ${name}`,
  } : Skip)
  async getOne(@Arg(`${name}Id`) id: number): Promise<E | undefined> {
    return await this.entity.findOne(id);
  }
}
```

Your use case is super rare and I'm not convinced about it 😕

**Comment by MichalLytek** [comment]
I found my earlier solution for skipping decorators, less ugly than the `Skip` :wink:
https://github.com/MichalLytek/type-graphql/issues/246#issuecomment-459717235

```ts
@Resolver(() => entity, { isAbstract: true })
abstract class BaseResolver {
  @If(
    !emitDelete,
    Query(() => entity, {
      name: `get${name}`,
      description: `Returns a single ${name}`,
    }),
  )
  async getOne(@Arg(`${name}Id`) id: number): Promise<E | undefined> {
    return await this.entity.findOne(id);
  }
}
```

But I still think that you should use the class mixins to compose the base resolver conditionally.

So closing this as out of scope as it leads to less readable code 🔒

**Pull request closed without merging**
