### PR TITLE
Add npm script for running an example

### PR DESCRIPTION
**Pull request by jhanggi**
There didn't seem to be an obvious way of running the examples. This is what I came up with while working on #1448.

If there's an even easier way, I'd love to hear it

### CODE REVIEW

**Comment by MichalLytek** [comment]
Just press F5 and choose example to run (in debug mode)

**Comment by carlocorradini** [comment]
Can we close this?
Maybe we can add `F5 on VSCode` in examples's README? @MichalLytek

**Comment by jhanggi** [comment]
I'm fine closing this. I would definitely appreciate some documentation around how to run the examples, I likely never would have found the F5 thing on my own. 

I use VSCode, but maybe there are people out there who don't. Is there a way for them to start the examples?

**Comment by carlocorradini** [comment]
Yeah docs on this is super.
After PR #1400 is merged:
```sh
mpm run build:examples
node examples/build/cjs/examples/[NAMEOFTHEEXAMPLE]/index.js
```

**Comment by MichalLytek** [comment]
The examples are runable by `ts-node` directly. We can add an info on "examples" page, just like it is for Prisma integration:
https://prisma.typegraphql.com/docs/examples

I don't like the idea of npm script that requires passing args. It's much easier to do `cd dir` and `ts-node ./index.ts`, if not using F5 debug mode 😉

**Pull request closed without merging**
